Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Collecting bumpversion==0.5.3
  Downloading http://localhost/packages/2.7/b/bumpversion/bumpversion-0.5.3-py2.py3-none-any.whl
Installing collected packages: bumpversion
Successfully installed bumpversion-0.5.3
Traceback (most recent call last):
  File "__tmpfile__.py", line 1, in <module>
    import pkg_resources;
ImportError: No module named pkg_resources
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Package search: {'_pypi_ordering': False, 'version': '0.5.3', 'name': 'bumpversion', 'summary': 'Version-bump your software with a single command!'}
Creating standard recipe for bumpversion-0.5.3
Using url https://pypi.python.org/packages/source/b/bumpversion/bumpversion-0.5.3.tar.gz (16 KB) for bumpversion.
Downloading bumpversion
Using cached download
Unpacking bumpversion...
done
working in /tmp/tmpceRwoCconda_skeleton_bumpversion-0.5.3.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.0. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup
ImportError: No module named setuptools

The following NEW packages will be INSTALLED:

    numpy:  1.9.2-py27_0
    pyyaml: 3.11-py27_1 
    yaml:   0.1.6-0     

Linking packages ...
[                    ]|                                                  |   0%[yaml                ]|                                                  |   0%[numpy               ]|################                                  |  33%[pyyaml              ]|#################################                 |  66%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmpceRwoCconda_skeleton_bumpversion-0.5.3.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpceRwoCconda_skeleton_bumpversion-0.5.3.tar.gz/bumpversion-0.5.3
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install bumpversion==0.5.3
Getting dependencies...
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-pipbuild", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 80, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 349, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 360, in execute
    build_package(package, version, noarch_python=args.noarch_python)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 304, in build_package
    noarch_python=noarch_python)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 240, in make_recipe
    depends = get_all_dependencies(package, version)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 219, in get_all_dependencies
    output = subprocess.check_output(cmd3args)
  File "/home/ubuntu/miniconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/ubuntu/miniconda/envs/_pipbuild_/bin/python', '__tmpfile__.py']' returned non-zero exit status 1
