Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Collecting influxdb==2.6.0
  Could not find a version that satisfies the requirement influxdb==2.6.0 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.2, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.2.0, 2.3.0)
No matching distribution found for influxdb==2.6.0
Package search: {'_pypi_ordering': False, 'version': '2.6.0', 'name': 'influxdb', 'summary': 'InfluxDB client'}
Creating standard recipe for influxdb-2.6.0
Using url https://pypi.python.org/packages/source/i/influxdb/influxdb-2.6.0.tar.gz (44 KB) for influxdb.
Downloading influxdb
Unpacking influxdb...
done
working in /tmp/tmppkX4WDconda_skeleton_influxdb-2.6.0.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.0. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    packages=find_packages(exclude=['tests']),
NameError: name 'find_packages' is not defined

Applying patch: '/tmp/tmppkX4WDconda_skeleton_influxdb-2.6.0.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmppkX4WDconda_skeleton_influxdb-2.6.0.tar.gz/influxdb-2.6.0
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install influxdb==2.6.0
Error: Could not pip install influxdb==2.6.0
