Warning, the following versions were found for plone.browserlayer
2.1.5
2.1.4
2.1.3
2.1.2
2.1.1
2.1
2.0.1
2.0
1.0.1
1.0.0
1.0rc4
1.0rc3
1.0rc2
1.0rc1
1.0b3
1.0b2
1.0b1
Using 2.1.5
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/plone.browserlayer/plone.browserlayer-2.1.5.tar.gz (15 KB) for plone.browserlayer.
Downloading plone.browserlayer
Using cached download
Unpacking plone.browserlayer...
done
working in /tmp/tmp_7ruNSconda_skeleton_plone.browserlayer-2.1.5.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


The following NEW packages will be INSTALLED:

    numpy:  1.9.2-py27_0
    pyyaml: 3.11-py27_1 
    yaml:   0.1.6-0     

Linking packages ...
[                    ]|                                                  |   0%[yaml                ]|                                                  |   0%[numpy               ]|################                                  |  33%[pyyaml              ]|#################################                 |  66%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmp_7ruNSconda_skeleton_plone.browserlayer-2.1.5.tar.gz/pypi-distutils.patch'
Warning, the following versions were found for plone.app.testing
5.0b4
5.0b3
5.0b2
5.0b1
5.0a2
5.0a1
4.2.5
4.2.4
4.2.3
4.2.2
4.2.1
4.2
4.0.2
4.0.1
4.0
4.0a6
4.0a5
4.0a4
4.0a3
3.0a1
1.0a2
1.0a1
Using 5.0b4
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/plone.app.testing/plone.app.testing-5.0b4.tar.gz (80 KB) for plone.app.testing.
Downloading plone.app.testing
Using cached download
Unpacking plone.app.testing...
done
working in /tmp/tmptcY4j7conda_skeleton_plone.app.testing-5.0b4.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmptcY4j7conda_skeleton_plone.app.testing-5.0b4.tar.gz/pypi-distutils.patch'
Error: Could not parse: plone.testing [zca,security,zodb,z2]
