Warning, the following versions were found for plone.app.locales
5.0
4.3.6
4.3.5
4.3.4
4.3.3
4.3.2
4.3.1
4.3
4.2.5
4.2.4
4.2.3
4.2.2
4.0.15
4.0.14
4.0.13
4.0.12
4.0.11
4.0.10
4.0.9
4.0.8
4.0.7
4.0.6
4.0.5
4.0.4
4.0.3
4.0.2
4.0.1
4.0.0
4.0.0rc1
4.0.0b5
4.0.0b4
4.0.0b3
4.0.0b1
4.0.0a3
4.0.0a2
4.0.0a1
3.3.15
3.3.14
3.3.13
3.3.12
3.3.11
3.3.10
3.3.9
3.3.8
3.3.7
3.3.6
3.3.5
3.3.4
3.3.3
3.3.2
3.3.1
3.3.0
3.2.0
3.1.4
Using 5.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/plone.app.locales/plone.app.locales-5.0.tar.gz (6.5 MB) for plone.app.locales.
Downloading plone.app.locales
Using cached download
Unpacking plone.app.locales...
done
working in /tmp/tmp3uOlyyconda_skeleton_plone.app.locales-5.0.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

The following NEW packages will be INSTALLED:

    numpy:  1.9.2-py27_0
    pyyaml: 3.11-py27_1 
    yaml:   0.1.6-0     

Linking packages ...
[                    ]|                                                  |   0%[yaml                ]|                                                  |   0%[numpy               ]|################                                  |  33%[pyyaml              ]|#################################                 |  66%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmp3uOlyyconda_skeleton_plone.app.locales-5.0.tar.gz/pypi-distutils.patch'
Writing recipe for plone.app.locales
Done
