Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/commands/install.py", line 268, in run
    wheel_cache
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 268, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 207, in from_line
    wheel_cache=wheel_cache)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 66, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse
    reqs = list(parse_requirements(s))
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements
    "version spec")
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'extensionclass==>=4.1.1', 'at', '==>=4.1.1')

Package search: {'_pypi_ordering': False, 'version': '3.0.6', 'name': 'plone.app.content', 'summary': 'Content Views for Plone'}
Creating standard recipe for plone.app.content-3.0.6
Converting recipe in /home/ubuntu/pypi-conda-builds/plone.app.content
package = plone.app.content
   dependencies = [u'acquisition', u'products.cmfcore >=2.2.0dev', u'products.cmfdynamicviewfti', u'products.cmfplone', u'zope2', u'plone.app.widgets >=2.0.0.dev0', u'plone.batching', u'plone.i18n', u'plone.memoize', u'zope.component', u'zope.container', u'zope.event', u'zope.i18n', u'zope.i18nmessageid', u'zope.interface', u'zope.lifecycleevent', u'zope.publisher', u'zope.schema', u'zope.viewlet', u'plone.protect']
Creating standard recipe for acquisition
Converting recipe in /home/ubuntu/pypi-conda-builds/acquisition
package = acquisition
   dependencies = [u'extensionclass >=4.1.1', u'zope.interface']
Creating standard recipe for extensionclass->=4.1.1
Error: Version >=4.1.1 of extensionclass is not available on PyPI.

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install extensionclass==>=4.1.1
Error: Could not pip install extensionclass==>=4.1.1
