products.ploneformgen not found, trying Products.PloneFormGen
Warning, the following versions were found for Products.PloneFormGen
1.8.0.alpha1
1.7.17
1.7.16
1.7.15
1.7.14
1.7.12
1.7.11
1.7.10
1.7.9
1.7.8
1.7.7
1.7.6
1.7.5
1.7.4
1.7.3
1.7.2
1.7.1
1.7.0
1.7rc1
1.7b6
1.7b5
1.7b4
1.7b3
1.7b2
1.7b1
1.7a2
1.7a1
1.6.8
1.6.7
1.6.6
1.6.5
1.6.4
1.6.3
1.6.2
1.6.1
1.6.0
1.6.0b5
1.6.0b4
1.6.0b3
1.6.0b2
1.6.0b1
1.5.5
1.5.4
1.5.3
1.5.2
1.5.1
1.5.0
1.5rc2
1.5rc1
1.5b5
1.5b4
1.5b3
1.5b2
1.5b1
1.2.7
1.2.6
1.2.5
1.2.4
1.2.3
1.2.2
Using 1.8.0.alpha1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/P/Products.PloneFormGen/Products.PloneFormGen-1.8.0.alpha1.zip (711 KB) for Products.PloneFormGen.
Downloading Products.PloneFormGen
Unpacking Products.PloneFormGen...
done
working in /tmp/tmpmFSDwfconda_skeleton_Products.PloneFormGen-1.8.0.alpha1.zip
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


The following NEW packages will be INSTALLED:

    numpy:  1.9.2-py27_0
    pyyaml: 3.11-py27_1 
    yaml:   0.1.6-0     

Linking packages ...
[                    ]|                                                  |   0%[yaml                ]|                                                  |   0%[numpy               ]|################                                  |  33%[pyyaml              ]|#################################                 |  66%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmpmFSDwfconda_skeleton_Products.PloneFormGen-1.8.0.alpha1.zip/pypi-distutils.patch'
WARNING: Could not add entry points. They were:

      # -*- Entry points: -*-
      [z3c.autoinclude.plugin]
      target = plone
      
Warning, the following versions were found for plone.testing
4.0.13
4.0.12
4.0.11
4.0.10
4.0.9
4.0.8
4.0.7
4.0.6
4.0.5
4.0.4
4.0.3
4.0.2
4.0.1
4.0
4.0a6
4.0a5
4.0a4
4.0a3
3.0a2
3.0a1
1.0a2
1.0a1
Using 4.0.13
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/plone.testing/plone.testing-4.0.13.zip (149 KB) for plone.testing.
Downloading plone.testing
Using cached download
Unpacking plone.testing...
done
working in /tmp/tmp_USByzconda_skeleton_plone.testing-4.0.13.zip
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


Applying patch: '/tmp/tmp_USByzconda_skeleton_plone.testing-4.0.13.zip/pypi-distutils.patch'
Warning, the following versions were found for zope.publisher
4.2.1
4.2.0
4.1.0
4.0.0
4.0.0a4
4.0.0a3
4.0.0a2
4.0.0a1
3.13.4
3.13.3
3.13.2
3.13.1
3.13.0
3.12.6
3.12.5
3.12.4
3.12.3
3.12.2
3.12.1
3.12.0
3.11.0
3.10.1
3.10.0
3.9.3
3.9.2
3.9.1
3.9.0
3.8.0
3.7.0
3.6.4
3.6.3
3.6.2
3.6.1
3.6.0
3.5.8
3.5.7
3.5.6
3.5.5
3.5.4
3.5.3
3.5.2
3.5.1
3.5.0
3.4.10
3.4.9
3.4.8
3.4.7
3.4.6
3.4.5
3.4.4
3.4.3
3.4.2
3.4.1
3.4.1b2
3.3.3
Using 4.2.1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/z/zope.publisher/zope.publisher-4.2.1.tar.gz (94 KB) for zope.publisher.
Downloading zope.publisher
Using cached download
Unpacking zope.publisher...
done
working in /tmp/tmp8fq3ihconda_skeleton_zope.publisher-4.2.1.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


Applying patch: '/tmp/tmp8fq3ihconda_skeleton_zope.publisher-4.2.1.tar.gz/pypi-distutils.patch'
WARNING: Could not add entry points. They were:

[paste.app_factory]
main = zope.publisher.paste:Application

[zope.publisher.publication_factory]
sample = zope.publisher.tests.test_paste:SamplePublication

Warning, the following versions were found for zope.security
4.0.3
4.0.2
4.0.1
4.0.0
4.0.0b1
4.0.0a5
4.0.0a4
4.0.0a3
4.0.0a2
4.0.0a1
3.9.0
3.8.5
3.8.4
3.8.3
3.8.2
3.8.1
3.8.0
3.7.4
3.7.3
3.7.2
3.7.1
3.7.0
3.6.3
3.6.2
3.6.1
3.6.0
3.5.2
3.5.1
3.5.0
3.4.3
3.4.2
3.4.1
3.4.0
3.4.0b5
Using 4.0.3
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/z/zope.security/zope.security-4.0.3.tar.gz (849 KB) for zope.security.
Downloading zope.security
Using cached download
Unpacking zope.security...
done
working in /tmp/tmpq3Iypsconda_skeleton_zope.security-4.0.3.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


Applying patch: '/tmp/tmpq3Iypsconda_skeleton_zope.security-4.0.3.tar.gz/pypi-distutils.patch'
Using url https://pypi.python.org/packages/source/z/zope.untrustedpython/zope.untrustedpython-4.0.0.zip (16 KB) for zope.untrustedpython.
Downloading zope.untrustedpython
Using cached download
Unpacking zope.untrustedpython...
done
working in /tmp/tmpcYytw6conda_skeleton_zope.untrustedpython-4.0.0.zip
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


Applying patch: '/tmp/tmpcYytw6conda_skeleton_zope.untrustedpython-4.0.0.zip/pypi-distutils.patch'
Warning, the following versions were found for zope.location
4.0.3
4.0.2
4.0.1
4.0.0
3.9.1
3.9.0
3.8.2
3.8.1
3.8.0
3.7.1
3.7.0
3.6.0
3.5.5
3.5.4
3.5.3
3.5.2
3.5.1
3.5.0
3.4.0
3.4.0b2
Using 4.0.3
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/z/zope.location/zope.location-4.0.3.tar.gz (150 KB) for zope.location.
Downloading zope.location
Using cached download
Unpacking zope.location...
done
working in /tmp/tmpCgv37Lconda_skeleton_zope.location-4.0.3.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


Applying patch: '/tmp/tmpCgv37Lconda_skeleton_zope.location-4.0.3.tar.gz/pypi-distutils.patch'
Warning, the following versions were found for zope.component
4.2.2
4.2.1
4.2.0
4.1.0
4.0.2
4.0.1
4.0.0
3.12.1
3.12.0
3.11.0
3.10.0
3.9.5
3.9.4
3.9.3
3.9.2
3.9.1
3.9.0
3.8.0
3.7.1
3.7.0
3.6.0
3.5.1
3.5.0
3.4.0
3.4dev-r72749
3.4dev-r72748
3.4dev-r72747
3.4dev-r72605
Using 4.2.2
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/z/zope.component/zope.component-4.2.2.tar.gz (534 KB) for zope.component.
Downloading zope.component
Using cached download
Unpacking zope.component...
done
working in /tmp/tmpMrxm3Oconda_skeleton_zope.component-4.2.2.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmpMrxm3Oconda_skeleton_zope.component-4.2.2.tar.gz/pypi-distutils.patch'
Error: Could not find any versions of package zope.component[zcml]
