Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Collecting python-glanceclient==0.19.0
  Could not find a version that satisfies the requirement python-glanceclient==0.19.0 (from versions: 0.1.1, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0)
No matching distribution found for python-glanceclient==0.19.0
Package search: {'_pypi_ordering': False, 'version': '0.19.0', 'name': 'python-glanceclient', 'summary': 'OpenStack Image API Client Library'}
Creating standard recipe for python-glanceclient-0.19.0
Using url https://pypi.python.org/packages/source/p/python-glanceclient/python-glanceclient-0.19.0.tar.gz (136 KB) for python-glanceclient.
Downloading python-glanceclient
Using cached download
Unpacking python-glanceclient...
done
working in /tmp/tmpOBJKuCconda_skeleton_python-glanceclient-0.19.0.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.0. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    import setuptools
ImportError: No module named setuptools

Applying patch: '/tmp/tmpOBJKuCconda_skeleton_python-glanceclient-0.19.0.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpOBJKuCconda_skeleton_python-glanceclient-0.19.0.tar.gz/python-glanceclient-0.19.0
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install python-glanceclient==0.19.0
Error: Could not pip install python-glanceclient==0.19.0
