Warning, the following versions were found for zope.index
4.1.0
4.0.1
4.0.0
3.6.4
3.6.3
3.6.2
3.6.1
3.6.0
3.5.2
3.5.1
3.5.0
3.4.1
3.4.0
3.4dev-r72927
Using 4.1.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/z/zope.index/zope.index-4.1.0.tar.gz (66 KB) for zope.index.
Downloading zope.index
Using cached download
Unpacking zope.index...
done
working in /tmp/tmpiTwdNZconda_skeleton_zope.index-4.1.0.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


The following NEW packages will be INSTALLED:

    numpy:  1.9.2-py27_0
    pyyaml: 3.11-py27_1 
    yaml:   0.1.6-0     

Linking packages ...
[                    ]|                                                  |   0%[yaml                ]|                                                  |   0%[numpy               ]|################                                  |  33%[pyyaml              ]|#################################                 |  66%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmpiTwdNZconda_skeleton_zope.index-4.1.0.tar.gz/pypi-distutils.patch'
Warning, the following versions were found for transaction
1.4.4
1.4.3
1.4.1
1.4.0
1.4.0b1
1.3.0
1.2.0
1.1.1
1.1.0
1.0.1
1.0.0
1.0a1
Using 1.4.4
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/t/transaction/transaction-1.4.4.tar.gz (59 KB) for transaction.
Downloading transaction
Using cached download
Unpacking transaction...
done
working in /tmp/tmpRWqtEyconda_skeleton_transaction-1.4.4.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


Applying patch: '/tmp/tmpRWqtEyconda_skeleton_transaction-1.4.4.tar.gz/pypi-distutils.patch'
WARNING: Could not add entry points. They were:
      
zodb not found, trying ZODB
Warning, the following versions were found for ZODB
4.2.0
4.2.0b1
4.1.0
4.0.1
4.0.0
4.0.0b3
4.0.0b2
4.0.0b1
4.0.0a4
4.0.0a3
4.0.0a2
4.0.0a1
Using 4.2.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/Z/ZODB/ZODB-4.2.0.tar.gz (399 KB) for ZODB.
Downloading ZODB
ZODB-4.2.0.tar   0% |                              | ETA:  --:--:--   0.00  B/sZODB-4.2.0.tar   4% |#                              | ETA:  0:00:00  40.54 MB/sZODB-4.2.0.tar   8% |##                             | ETA:  0:00:00   5.61 MB/sZODB-4.2.0.tar  12% |###                            | ETA:  0:00:00   4.04 MB/sZODB-4.2.0.tar  16% |####                           | ETA:  0:00:00   5.28 MB/sZODB-4.2.0.tar  20% |######                         | ETA:  0:00:00   4.45 MB/sZODB-4.2.0.tar  24% |#######                        | ETA:  0:00:00   5.25 MB/sZODB-4.2.0.tar  28% |########                       | ETA:  0:00:00   5.98 MB/sZODB-4.2.0.tar  32% |#########                      | ETA:  0:00:00   5.32 MB/sZODB-4.2.0.tar  36% |###########                    | ETA:  0:00:00   5.91 MB/sZODB-4.2.0.tar  40% |############                   | ETA:  0:00:00   6.48 MB/sZODB-4.2.0.tar  44% |#############                  | ETA:  0:00:00   7.05 MB/sZODB-4.2.0.tar  48% |##############                 | ETA:  0:00:00   6.32 MB/sZODB-4.2.0.tar  52% |################               | ETA:  0:00:00   6.72 MB/sZODB-4.2.0.tar  56% |#################              | ETA:  0:00:00   7.14 MB/sZODB-4.2.0.tar  60% |##################             | ETA:  0:00:00   7.60 MB/sZODB-4.2.0.tar  64% |###################            | ETA:  0:00:00   8.06 MB/sZODB-4.2.0.tar  68% |#####################          | ETA:  0:00:00   7.37 MB/sZODB-4.2.0.tar  72% |######################         | ETA:  0:00:00   7.76 MB/sZODB-4.2.0.tar  76% |#######################        | ETA:  0:00:00   8.04 MB/sZODB-4.2.0.tar  80% |########################       | ETA:  0:00:00   8.38 MB/sZODB-4.2.0.tar  84% |##########################     | ETA:  0:00:00   8.75 MB/sZODB-4.2.0.tar  88% |###########################    | ETA:  0:00:00   9.11 MB/sZODB-4.2.0.tar  92% |############################   | ETA:  0:00:00   9.48 MB/sZODB-4.2.0.tar  96% |#############################  | ETA:  0:00:00   8.93 MB/sZODB-4.2.0.tar 100% |###############################| ETA:  0:00:00   9.25 MB/sZODB-4.2.0.tar 100% |###############################| Time: 0:00:00   9.20 MB/s
Unpacking ZODB...
done
working in /tmp/tmpYarz4pconda_skeleton_ZODB-4.2.0.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


Applying patch: '/tmp/tmpYarz4pconda_skeleton_ZODB-4.2.0.tar.gz/pypi-distutils.patch'
WARNING: Could not add entry points. They were:

      [console_scripts]
      fsdump = ZODB.FileStorage.fsdump:main
      fsoids = ZODB.scripts.fsoids:main
      fsrefs = ZODB.scripts.fsrefs:main
      fstail = ZODB.scripts.fstail:Main
      repozo = ZODB.scripts.repozo:main
      
Warning, the following versions were found for zodbpickle
0.6.0
0.5.2
0.5.1
0.5.0
0.4.4
0.4.3
0.4.2
0.4.1
0.4
0.3
0.2
0.1.0
Using 0.6.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/z/zodbpickle/zodbpickle-0.6.0.tar.gz (218 KB) for zodbpickle.
Downloading zodbpickle
Using cached download
Unpacking zodbpickle...
done
working in /tmp/tmpD151m6conda_skeleton_zodbpickle-0.6.0.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


Applying patch: '/tmp/tmpD151m6conda_skeleton_zodbpickle-0.6.0.tar.gz/pypi-distutils.patch'
Warning, the following versions were found for zdaemon
4.1.0
4.0.1
4.0.0
4.0.0a1
3.0.5
3.0.4
3.0.3
3.0.2
3.0.1
3.0.0
2.0.7
2.0.6
2.0.5
2.0.4
2.0.3
2.0.2
2.0.1
2.0.0
2.0a6
2.0a2
Using 4.1.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/z/zdaemon/zdaemon-4.1.0.zip (73 KB) for zdaemon.
Downloading zdaemon
Using cached download
Unpacking zdaemon...
done
working in /tmp/tmpB3NYz0conda_skeleton_zdaemon-4.1.0.zip
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


Applying patch: '/tmp/tmpB3NYz0conda_skeleton_zdaemon-4.1.0.zip/pypi-distutils.patch'
WARNING: Could not add entry points. They were:

[console_scripts]
zdaemon = zdaemon.zdctl:main

Warning, the following versions were found for zc.customdoctests
1.0.1
1.0.0
0.1.0
Using 1.0.1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/z/zc.customdoctests/zc.customdoctests-1.0.1.zip (15 KB) for zc.customdoctests.
Downloading zc.customdoctests
Using cached download
Unpacking zc.customdoctests...
done
working in /tmp/tmpoJA3Gqconda_skeleton_zc.customdoctests-1.0.1.zip
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


Applying patch: '/tmp/tmpoJA3Gqconda_skeleton_zc.customdoctests-1.0.1.zip/pypi-distutils.patch'
Warning, the following versions were found for python-spidermonkey
0.0.10
0.0.9
0.0.8
0.0.7
0.0.6
0.0.5
0.0.4
0.0.3
0.0.2
0.0.1a
Using 0.0.10
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/python-spidermonkey/python-spidermonkey-0.0.10.tar.gz (769 KB) for python-spidermonkey.
Downloading python-spidermonkey
Using cached download
Unpacking python-spidermonkey...
done
working in /tmp/tmpeZ0XaWconda_skeleton_python-spidermonkey-0.0.10.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 186, in <module>
    **platform_config()
  File "setup.py", line 143, in platform_config
    return nspr_config(config=config)
  File "setup.py", line 87, in nspr_config
    return pkg_config("nspr", config)
  File "setup.py", line 59, in pkg_config
    raise RuntimeError("No package configuration found for: %s" % pkg_name)
RuntimeError: No package configuration found for: nspr

Applying patch: '/tmp/tmpeZ0XaWconda_skeleton_python-spidermonkey-0.0.10.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpeZ0XaWconda_skeleton_python-spidermonkey-0.0.10.tar.gz/python-spidermonkey-0.0.10
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
